# fly-io-metadata Makefile

CAPABILITY_ID = "protochron:fly_metadata"
NAME = "fly-io-metadata"
VENDOR = "Cosmonic"
PROJECT = fly_io_metadata
VERSION = 0.1.0
REVISION = 0

include ./provider.mk

test::
	cargo clippy --all-targets --all-features

