#!/bin/bash

creds="$NATS_CREDS"
if [ -n "$creds" ]; then
	echo "Using credentials from environment variable"
	echo -e "$creds" > /etc/service/nats/nats.creds
else
	echo "No credentials provided"
	exit 1
fi

nats-server -js -c /etc/service/nats/nats.conf
