#!/bin/bash

creds="$NATS_CREDS"
if [ -n "$creds" ]; then
	echo "Using credentials from environment variable"
	echo -e "$creds" > /etc/service/nats/nats.creds
else
	echo "No credentials provided"
	exit 1
fi

if [ -n "$NATS_ADDR" ]; then
  export NATS_ADDR="$NATS_ADDR"
else
  echo "No cluster configuration provided"
  exit 1
fi

nats-server -js -c /etc/service/nats/nats.conf
