apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: argocon-fly-demo
  annotations:
    version: v0.2.0
    description: "Demo for ArgoCon EU 2024 demonstrating deploying a wasmCloud application to fly.io"
    experimental: "true"
spec:
  components:
    - name: fly-hello
      type: actor
      properties:
        image: ghcr.io/protochron/argocd-demo/fly-hello:0.4.0
      traits:
        # Govern the spread/scheduling of the actor
        - type: daemonscaler
          properties:
            replicas: 20
            spread:
              - name: fly
                requirements:
                  cloud: fly.io
        # Link the HTTP server, and inform it to listen on port 8080
        # on the local machine
        - type: linkdef
          properties:
            target: httpserver
            values:
              address: 0.0.0.0:8080
        - type: linkdef
          properties:
            target: fly-metadata

    # Add a capability provider that mediates HTTP access
    - name: httpserver
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpserver:0.19.1
        contract: wasmcloud:httpserver
      traits:
        - type: daemonscaler
          properties:
            instances: 1
            spread:
              - name: fly
                requirements:
                  cloud: fly.io

    # Capability provider to expose a Fly Machine's environment variables
    - name: fly-metadata
      type: capability
      properties:
        image: ghcr.io/protochron/argocd-demo/fly-io-metadata:0.3.1
        contract: protochron:fly_metadata
      traits:
        - type: daemonscaler
          properties:
            instances: 1
            spread:
              - name: fly
                requirements:
                  cloud: fly.io
