name: kind-metadata

on:
  pull_request:
    paths:
      - 'kind-metadata/**'
  merge_group:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - kind-metadata-v*
env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo clippy --no-deps
        working-directory: kind-metadata

  build:
    needs:
      - lint
    permissions:
      packages: write
      id-token: write
      attestations: write
      contents: read
    uses: ./.github/workflows/provider.yml
    with:
      name: kind-metadata
    secrets:
      issuer: ${{secrets.COSMONIC_LABS_SIGNING_ACCOUNT}}
      subject: ${{secrets.FLY_IO_PROVIDER_KEY}}
